### ISSUE TITLE
ECR support fails with Concourse 2.7.0

### ISSUE THREAD

**Issue by mikelorant** [concourse/docker-image-resource#101]
Concourse 2.7.0 uses Docker 1.13.0. Docker 1.13.0 and the Amazon ECR credential helper are no longer compatible. This is a known issue and details can be found here:

https://github.com/awslabs/amazon-ecr-credential-helper/issues/23

This is preventing Concourse from being able to build images from a ECR registry.

**Comment by ykrevnyi** [comment]
+1
We cannot use base images from ECR.

@vito It is possible for you to take a look at this one, please?

**Comment by martinsbalodis** [comment]
Didn't have the chance to see it work in 2.6.x but I cannot get it to work in 2.7.0 also. I am getting an error message like this - `no basic auth credentials`.

**Comment by monson** [comment]
+1
base image from ECR is failing

**Comment by monson** [comment]
@vito @ykrevnyi is there any workarounds for this..

**Comment by joshzarrabi** [comment]
This was supposed to be fixed by us bumping the credentials helper in #107 

For some reason, this doesn't seem to have completely fixed it, so instead we've tagged the docker-image-resource on dockerhub with `docker-1.12.6` from when the resource was still using that version of docker (which isn't plagued with this ECR issue)

While we try to find a more permanent fix you can use a get-around by adding:

```
resource_types:
  - name: docker-image
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: docker-1.12.6
```

to each of your pipelines that needs it.

**Comment by bacoboy** [comment]
Verified this is broken in 2.7.3 when doing `FROM` an ECR image.  @joshzarrabi workaround works for us.

**Comment by chendrix** [comment]
@mikelorant @bacoboy @jadekler can one of you verify whether or not this is still an issue in the latest versions?

**Comment by bacoboy** [comment]
@chendrix it was broken in 3.0.1.  I asked about it in slack and you opened #1178.  What's changed?  

The workaround in #1178 works, but only if you call the image `docker-image-2`.  We tried calling it something else and it didn't like it.

**Comment by chendrix** [comment]
@bacoboy got it, so you're still seeing the issue with the resource itself, and are forced to use the downgraded docker version.

thanks, that's what I needed to know.

**Comment by thebeefcake** [comment]
Seeing here also on 3.0.1, have tried the duplicate image resource

**Comment by richarddowner** [comment]
Using the fix from @joshzarrabi worked when I was using concourse version `2.7.0`
We have just updated to version `3.1.0` as we require the new encryption feature. 
Using version `3.1.0` we get this error when using the fix 
```
mount: permission denied (are you root?)
```

**Comment by stefan-de-koning** [comment]
Still having issues using 3.3.0. Pulling images from ECR for task execution works fine. But I am unable to build images in which the Dockerfile contains a FROM that references a ECR repository. I tried the docker-image-2 workaround but this did not make any difference.

The docker-image build task fails on the pull:
`Sending build context to Docker daemon  30.06MB
Step 1/3 : FROM xxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxx:latest
Pulling repository xxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxx
unauthorized: authentication required`
