### ISSUE TITLE
Logging onto Docker earlier

### ISSUE THREAD

**Issue by pronoiac** [concourse/docker-image-resource#103]
A common issue with our Docker builds is: 

```
Error response from daemon: Get https://registry-1.docker.io/v2/: toomanyrequests: too many failed login attempts for username or IP address
```

Can we move the login earlier? We'd like for this to happen *before* the build, rather than at the end, to avoid the resources spent on building an image that we then drop on the floor because we can't upload it.

**Comment by vito** [comment]
We already log in immediately.

https://github.com/concourse/docker-image-resource/blob/master/assets/out#L49

Is it possible someone has the wrong credentials for your dockerhub account and causes a lockout between when we login and when we do a push?
