### ISSUE TITLE
how to use AWS ECR image as base image for Dockerfile

### ISSUE THREAD

**Issue by thaniyarasu** [concourse/docker-image-resource#105]
how to use AWS ECR image as base image for Dockerfile ??

     config:
       platform: linux
       inputs:
       - name: demo
       outputs:
       - name: workspace
       run:
         path: /bin/bash
         args:
         - -c
         - |
           output_dir=workspace
           cat << EOF > "${output_dir}/Dockerfile"
           FROM 4574563542367.dkr.ecr.us-east-1.amazonaws.com/my/image
           ADD demo /tmp/demo
           RUN bundle install --gemfile=/tmp/demo/Gemfile
           RUN rm -rf /tmp/demo
           EOF
           cp -R ./demo "${output_dir}/demo"
   - put: release-docker-image

**Comment by joshzarrabi** [comment]
Closing. Same as #101
