### ISSUE TITLE
Add support for ECR IAM roles in task definitions

### ISSUE THREAD

**Issue by willejs** [concourse/docker-image-resource#109]
The docker container needs to be started with the environment variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` populated from the current environment

**Comment by vito** [comment]
I don't like the idea of magically propagating credentials from workers into every container that runs on them. It may make sense at first but once you start using the worker with multiple tenants you've now spread credentials to people who shouldn't have them.

Consolidating into https://github.com/concourse/concourse/issues/291
