### ISSUE TITLE
Missing ECR error handling, obfuscates API errors such as throttling limits

### ISSUE THREAD

**Issue by geezyx** [concourse/docker-image-resource#114]
Hello!

We have a fairly large deployment of concourse using custom resources from and building/pushing images to AWS ECR.  We recently discovered that we are running into throttling limits, but the error output was obfuscated due to a lack of error handling here:

https://github.com/concourse/docker-image-resource/blob/master/cmd/check/main.go#L47-L53

Can you please add pipeline feedback when ECR errors are encountered at the initial login?

Since the credentials simply don't get set following the login attempt when `err != nil`, the subsequent call produces an authentication error.  Here's the output we are getting, (account and image name removed):

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch manifest: Get https://<account#>.dkr.ecr.us-west-2.amazonaws.com/v2/<image>/manifests/latest: no basic auth credentials
```

**Comment by chendrix** [comment]
This is something that would be a wonderful PR to accept.

If you're interested, please start by looking at our [Contributing Guide](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md)

I've also attached this to the Help Wanted milestone.

**Comment by steelecliftonberry** [comment]
@vito Hey - you removed the 'Help Wanted' milestone. Is this something Pivotal are working on internally or are you still open to community PR?
