### ISSUE TITLE
ECR auth problem

### ISSUE THREAD

**Issue by jadekler** [concourse/docker-image-resource#116]
I'm using the `docker-image` resource and trying to push to AWS ECR. I've provided `aws_access_key_id` and `aws_secret_access_key` in the source configuration for the resource. However, I'm getting `no basic auth credentials` failure. Any ideas what's up with that?

**Comment by tiredpixel** [comment]
@jadekler, I just experienced this, too. After some debugging, including using the `docker-1.12.6` tag as detailed in https://github.com/concourse/docker-image-resource/issues/101 , but eventually I discovered it was simply an incorrect policy attached to my IAM user. :) That is to say, using `latest` tag works with `aws_access_key_id` and `aws_secret_access_key` set with no auth credentials using an ECR repository with no port (contrary to the documentation).

**Comment by chendrix** [comment]
@jadekler did you ever figure this out?

**Comment by chendrix** [comment]
Closing to keep things fresh

**Comment by ceason** [comment]
@chendrix I started by using the `AmazonEC2ContainerRegistryPowerUser` managed policy and had the same problem (`no basic auth`). After adding `ecr:BatchDeleteImage` everything works now!
