### ISSUE TITLE
Multiple FROM tags are not supported

### ISSUE THREAD

**Issue by farcaller** [concourse/docker-image-resource#117]
If multiple FROM tags are used, build aborts. E.g., given

```
FROM golang:alpine AS build-stage
COPY ./ /go/src/...
...
```

The error is:

```
Step 1 : FROM golang:alpine AS build-stage
Error parsing reference: "golang:alpine AS build-stage" is not a valid repository/tag
```

Should there be a new build with latest docker binary version?

**Comment by chendrix** [comment]
@farcaller where did you see that this is possible?

I don't see this syntax available in the [Dockerfile syntax](https://docs.docker.com/engine/reference/builder/#from) and we are using the latest version of docker [v17.05.0-ce](https://ci.concourse.ci/teams/main/pipelines/resources/jobs/docker-image-resource/builds/28)

**Comment by farcaller** [comment]
My bad, it's in CE Edge only for now: https://docs.docker.com/engine/userguide/eng-image/multistage-build/

Any change you could provide a docker-edge version of the resource?

**Comment by chendrix** [comment]
We have a (I think reasonable) hesitation to providing edge releases of external dependencies in our software.
