### ISSUE TITLE
Upgrade to docker 1.8.1

### ISSUE THREAD

**Issue by oppegard** [concourse/docker-image-resource#12]
I'm not sure if the resources are built on every release of concourse, or if it's a manual process. If it's manual, please rebuild the image to get the latest docker. Thanks!

**Comment by xoebus** [comment]
![screen shot 2015-08-17 at 17 45 41](https://cloud.githubusercontent.com/assets/38814/9319864/26d4b836-4508-11e5-88f3-cb921ce010ab.png)
