### ISSUE TITLE
RFC: add labels to metadata

### ISSUE THREAD

**Issue by endemics** [concourse/docker-image-resource#125]
Hi,

We're thinking about adding labels to the metadata structure that `/opt/resources/check` outputs, so we could easily access things like versions or git hash in the concourse UI by using labels following conventions like http://label-schema.org/rc1/

Before starting implementing this, I'd like to gauge if this would be useful to others and if there's interest to merge this in the project.

Cheers
Gildas

Edit: It should not be in `out` but in `check`.

**Comment by jtarchie** [comment]
@endemics, I'm not quite sure I follow the spec linked to. What is the problem you are solving by adding these labels?

**Comment by endemics** [comment]
Fair enough!

We are using docker images as deployment artifacts in our pipeline. Those docker images are not generated in concourse, but pulled from an internal registry/AWS ECR.

We want to make it easier to figure out what version of the image (and hence the code) is present in a particular stage of the pipeline or in a specific job build number.

The current solution only exposes the digest or the image hashes, which forces us to go back a few step and track which version of the code correspond to the said digest/image hash.

Exposing labels would enable us to do so as we can use it to expose app versions and git hashes for instance.

I was merely pointing at the label-schema as this seems like an emerging standard that validates using labels for such usage in the docker-verse (whether or not we end-up using their name space or not is irrelevant and just an implementation detail).

HTH

**Comment by endemics** [comment]
@jtarchie have you been able to revisit this issue since I've added more context? I'd love to be able to use metadata as per #128

**Comment by jtarchie** [comment]
Concourse already provides this mechanism by having a resource being able to `passed` down a pipeline. You can pass the code and the docker image in conjunction. Are you able to do that?

**Comment by PFacheris** [comment]
I'd be interested in metadata on the tag that was created, this would be easier to reference back to a build in the UI since most people think in terms of tags rather than digest.
