### ISSUE TITLE
Develop Documentation?

### ISSUE THREAD

**Issue by neezer** [concourse/docker-image-resource#127]
I've forked this repo because I have two enhancements I'd like to try out (and maybe open PRs back to here with), but I've been unable to get the image built on my local machine => deployed to my DockerHub account => able to pull into an actual pipeline to test with.

I've tried

```
docker build --rm -t neezer/docker-image-resource .
```

... which fails with

```
Sending build context to Docker daemon  8.708MB
Step 1/5 : FROM concourse/buildroot:iptables
 ---> 3d9a7966693d
Step 2/5 : ADD docker/ /usr/local/bin/
ADD failed: stat /var/lib/docker/tmp/docker-builder897773368/docker: no such file or directory
```

Looking at `/ci/build.yml`, seems it's expecting resources given by a pipeline... the source of which doesn't appear in this repo.

---

Would it be possible to get some documentation on how to do development on this resource? I'm happy to help author some of that documentation if someone would just help me to get things working. 😄

**Comment by xtremerui** [comment]
Closing as there is `Development` section added afterwards.
