### ISSUE TITLE
When registry mirror is set, resource still tries to talk to Dockerhub

### ISSUE THREAD

**Issue by theozaurus** [concourse/docker-image-resource#129]
Hi,

I think think this is a bug (although I may have misunderstood the `registry_mirror` option). When we set this option we were expecting all communications to go to that registry_mirror as opposed to Dockerhub (unless of course a Dockerfile explicitly loads from another address). However, we see that the resource still tries to connect to Dockerhub.

Looking at the code I suspect it is something to do with [`login`](https://github.com/concourse/docker-image-resource/blob/master/assets/out#L49). Here it appears to connect to Docker, even though a `registry_mirror` is specified. It does not connect to Docker though if the resource is from a private registry, and it will instead connect to that private registry.

Should setting the `registry_mirror` cause all communications that would go to Dockerhub to go to the mirror instead?

Thanks,

Theo

**Comment by chendrix** [comment]
`registry_mirror` is exactly that, a `mirror`, which is a fallback in case the one specified in your `repository:` parameter isn't set. 

You should be able to give the fully qualified `repository`, e.g. `https://my-private-repository.example.com:443/my-organization/my-image`
