### ISSUE TITLE
Cannot fetch existing images from repositoty

### ISSUE THREAD

**Issue by ykrevnyi** [concourse/docker-image-resource#130]
Hey guys,

Seems like `docker-image-resource` cannot fetch existing images from docker repository when there is no `latest` tag on any image.

Example:
```
Given I have a docker repository
and 10 images inside of this repository
and these 10 images are semantically versioned
When there is no `latest` tag on any image
and I pull new versions (run `fly cr`)
Then I see message `checked '<resource>'`
and there is no available versions in the resource
```

As soon as I tag any image as `latest` then `fly cr` will recognize all available versions.

Thanks

**Comment by chendrix** [comment]
Hi @ykrevnyi are you configuring a tag in your resource?

```
resources:
- name: foo
  type: docker-image
  source:
    repository: node
    tag: "3.5"

**Comment by ykrevnyi** [comment]
Thanks for reply @chendrix 
Closing this issue If it's expected behavior.
