### ISSUE TITLE
`tag` and `cache_tag` more flexible input support

### ISSUE THREAD

**Issue by zhenyulin** [concourse/docker-image-resource#132]
I'm currently trying to configure `cache_tag` with semver, which is in a file, however find that `cache_tag` input can only be a string, and there's no way in the job/task configuration to read the file as a string;

On the other hand, I also tried to use string to make `tag`, which turns out only accepting a file.

Would be great both fields can accept files and string.

**Comment by chendrix** [comment]
Hi there, the default for `cache_tag` is already to use what's been put in `tag`. So if you've set up `tag` with a file, you should not configure `cache_tag`, and it will already pull down the tag first.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
