### ISSUE TITLE
Strips out 'dev' directory *anywhere* in the image

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [concourse/docker-image-resource#142]
This line:

https://github.com/concourse/docker-image-resource/blob/36714019b65c545451eae10bfef693895c061048/assets/in#L80

...is intended to exclude only the toplevel `/dev` directory, however it seems to exclude them anywhere in the filesystem.

Example image with an issue: `bosh/bosh-load-tests@sha256:d67ecb7a412a409ae1afc4dbe61e435bb7efce5b48f814b4769713ad8a15e12f`

it should have files in `/usr/local/bosh-deployment/dev` , but it is empty.

**Comment by ryanbrainard** [comment]
Happened to stumble across this. The problem is you need the use the —anchored option with tar.

**Comment by xtremerui** [comment]
@ryanbrainard thx for the solution. Tested it locally and it works well.

**Comment by vito** [comment]
Ran into a problem with the fix; `tar` in Alpine doesn't have the `--anchored` option. Maybe we can install GNU tar?

**Comment by vito** [comment]
Should be resolved in v1.3.3.
