### ISSUE TITLE
Handle ambiguous repository names when pulling from Dockerhub

### ISSUE THREAD

**Issue by topherbullock** [concourse/docker-image-resource#146]
For official repositories, Dockerhub allows pulling the same repository using different names.
An example of this is the [OpenJDK](https://hub.docker.com/r/library/openjdk/) official repository.

When configured using `"library/openjdk"` as the repository, it will seem to succeed in pulling, but fail in  `/opt/resource/in` because according to `docker images` the repository name is just `"openjdk"`

```yaml
image_resource:
  type: docker-image
  source: {repository: library/openjdk}
```

```
Successfully pulled library/openjdk@sha256:5da842d59f76009fa27ffde06888ebd560c7ad17607d7cd1e52fc0757c9a45fb.

"docker inspect" requires at least 1 argument(s).
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects

resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
```

This can be solved by using the "official" repository name of just `"openjdk"`, but its hard to know that this is the solution without some digging.

```yaml
image_resource:
  type: docker-image
  source: {repository: openjdk}
```

Luckily `docker pull` tells us that the image pulled has a different repo name:

```
$ docker pull library/openjdk
Using default tag: latest
latest: Pulling from library/openjdk
06b22ddb1913: Pull complete
336c28b408ed: Pull complete
1f3e6b8d80c3: Pull complete
5ccc640979f6: Pull complete
14eaa20184e6: Pull complete
19a8522e2399: Pull complete
39ba9d7befca: Pull complete
635bf5037831: Pull complete
d1236c277f1c: Pull complete
Digest: sha256:5da842d59f76009fa27ffde06888ebd560c7ad17607d7cd1e52fc0757c9a45fb
Status: Downloaded newer image for openjdk:latest
```

Note the **Downloaded newer image for openjdk:latest** even though  `library/openjdk` was specified as the repo to pull, so we could use that information to infer the "real" name of the repo to pass to `docker images`

**Comment by GenPage** [comment]
I seem to have this issue regardless of using just the "official" name or `library/alpine` or `golang/alpine`. In my example, I am trying to pull `alpine`.

The other difference is I'm not setting this in a task using `image_resource`. This is being defined as a resource in the pipeline itself. 

The example has just `alpine` but even if I explicitly set `golang/alpine` it still pulls from `library/alpine`

```
- name: alpine
  type: docker-image
  source:
    repository: alpine
```
```
Pulling library/alpine@sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b...
sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b: Pulling from library/alpine
ff3a5c916c92: Pulling fs layer
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
Digest: sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b
Status: Downloaded newer image for alpine@sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b

Successfully pulled library/alpine@sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b.

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
```

**Comment by ghostsquad** [comment]
This is a discrepancy in docker, not in this resource. I think the fix here is not to use `library` in your repository when referring to official/library images.

**Comment by xtremerui** [comment]
On the top right https://hub.docker.com/_/openjdk it indicates pulling that image using 
```
docker pull openjdk
```
 Although pulling it by `library/openjdk` still works, one should always use `openjdk` as the image name.
