### ISSUE TITLE
in script doesn't correctly set the tag

### ISSUE THREAD

**Issue by edude03** [concourse/docker-image-resource#149]
The documentation for the `in` script says `/tag: The tag of the repository that was fetched.` however looking at the code [here](https://github.com/concourse/docker-image-resource/blob/master/assets/in#L32) it seems that the tag is set to latest if not specified by the user. 

My goal here is to use the tag to set the correct image to pull in the deploy step. Therefore I'd like the script to function as described.

**Comment by bcampoli** [comment]
I will +1 this issue. I need to use the real tag number.

**Comment by edude03** [comment]
For what its worth - I talked to @jtarchie about this and he said it was intended behaviour. My solution was to use the digest instead which is actually immutable and thus fits the use case better.
