### ISSUE TITLE
Protocol port of source config

### ISSUE THREAD

**Issue by mehtaphysical** [concourse/docker-image-resource#15]
Would you guys be opposed to being able to select a protocol as part of source config?

My issue right now is that I'm using a private docker repo that uses https (not http)

**Comment by vito** [comment]
Yeah, though even better might be to never assume either protocol and just try HTTPS first, falling back to HTTP if it fails. A bit more complicated, but fewer knobs to turn.

**Comment by mehtaphysical** [comment]
@vito sounds good to me. Would you accept a PR or are you working on it already?

**Comment by vito** [comment]
PR would be great, we're not actively doing much with this resource ourselves at the moment.

**Comment by vito** [comment]
Shouldn't be needed anymore (see https://github.com/concourse/docker-image-resource/pull/16#issuecomment-158713056).
