### ISSUE TITLE
question about testing

### ISSUE THREAD

**Issue by josebarn** [concourse/docker-image-resource#153]
Is there currently a way to build a docker image, store it in an output resource, _and not push it_ - giving me a chance to use the image in testing before pushing.

It appears that all examples I find are pushing then pulling back to test, or adding testing in the image - which seems like a hack to me. 

I don't want to ship tests.

Is there a way to do this currently?

**Comment by thebeefcake** [comment]
Hey @josebarn,

I have a pr up to add a dry run mode. To test if the image builds when doing PR testing etc.
https://github.com/concourse/docker-image-resource/pull/154

I guess this is a precursor to what you're talking about and building to an output dir.

**Comment by josebarn** [comment]
@pickledrick Awesome, that is exactly what I am looking for :)

**Comment by josebarn** [comment]
@pickledrick this will only save to the local repository - if I'm not mistaken, I actually have to rebuild the build step to push the image; Is that correct?
I guess it is a minor nit since I wanted to push the image that was tested... post testing. but then again, the build should be exactly the same (unless I do something silly like use `latest` and someone updates a base in between tasks...

**Comment by vito** [comment]
Consolidating this into https://stackoverflow.com/questions/41061180/is-it-possible-to-build-a-docker-image-without-pushing-it - I think the only thing missing here is for someone to create a de-facto standard task for doing this.
