### ISSUE TITLE
Upgrading Docker

### ISSUE THREAD

**Issue by novcn** [concourse/docker-image-resource#163]
There is a feature of Docker v17.09.0-ce that enables the use of the --chown flag on the docker COPY command. This would greatly speed up my pipelines. 

Is it possible to upgrade to the latest Docker? After poking around for a bit it's not clear to me where concourse installs Docker.

**Comment by jchesterpivotal** [comment]
It [appears that it's installed by the `Dockerfile` for the resource](https://github.com/concourse/docker-image-resource/blob/master/Dockerfile#L15).

**Comment by novcn** [comment]
Thank you @jchesterpivotal
