### ISSUE TITLE
Getting WARNING! Using --password via the CLI is insecure. Use --password-stdin when trying to put a docker-resource

### ISSUE THREAD

**Issue by rekaparathalwar** [concourse/docker-image-resource#168]
resources:

  - name: git-repo
    type: git
    source:
      branch: master
      private_key: |-
        -----BEGIN RSA PRIVATE KEY-----
        ----- Key here -------------
        -----END RSA PRIVATE KEY-----
      uri: <gitUrl>

  - name: docker-image
    type: docker-image
    source:
      password: <password>
      repository: <image name with repository>
      username: <username>

jobs:
  - name: test-docker
    plan:
      - get: git-repo
        trigger: true
      - put: docker-image
        params:
          build: git-repo/
          tag: 1.0.1

The pipeline works fine except that when it tries to put the docker-image it throws warning as 
"WARNING! Using --password via the CLI is insecure. Use --password-stdin."

Docker encourages using --password-stdin to login  to prevent the password from ending up in the shell’s history, or log-files. Can you please make the necessary changes so that we can avoid any password leaks

https://docs.docker.com/engine/reference/commandline/login/#extended-description

**Comment by marcelocorreia** [comment]
+1

**Comment by cedrox** [comment]
+1

**Comment by jfernandeze** [comment]
+1

**Comment by cappyzawa** [comment]
Sorry, I messed up this issue :(
I sent #172 to fix this.
