### ISSUE TITLE
docker-image-resource fails on cgroups error with alpine:edge

### ISSUE THREAD

**Issue by tanner-bruce** [concourse/docker-image-resource#174]
Rebuilding the docker-image-resource locally causes all builds to fail with `cgroups: cannot found cgroup mount destination: unknown`

alpine:edge is currently running 17.12. alpine:3.7 also fails, with docker version 17.10, however alpine:3.6 works as expected. 3.6 is running docker v17.05

May be worth considering using the official docker in docker image.

Tested with a very kosher pipeline and dockerfile (from alpine:3.6; apk add bash)

```WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Sending build context to Docker daemon  102.9MB
Step 1/2 : FROM alpine:edge
edge: Pulling from library/alpine
1eae7a7426b0: Pulling fs layer
1eae7a7426b0: Verifying Checksum
1eae7a7426b0: Download complete
1eae7a7426b0: Pull complete
Digest: sha256:79c2c5f6db53da44f90bb2731f29f725b5b14c378407a123776b6d3c76e6aebe
Status: Downloaded newer image for alpine:edge
 ---> 5c4fa780951b
Step 2/2 : RUN apk add --no-cache bash
 ---> Running in 9712894311cf
cgroups: cannot found cgroup mount destination: unknown```

**Comment by jamespamplin** [comment]
I found that locking the resource image to `alpine:3.7` worked for me, see: eeveebank/docker-image-resource@3fe6dfe70a8439007bc32621faf3606b0c9ca1c0
