### ISSUE TITLE
Please document why and how image is pulled after it is pushed

### ISSUE THREAD

**Issue by chrishiestand** [concourse/docker-image-resource#214]
I assume that a docker image is pulled after it is pushed in order to verify it is correctly pulled? I could only find that this was expected behavior here:

https://github.com/concourse/docker-image-resource/issues/36#issuecomment-228844892

I'm also new to concourse and I have been reviewing the `out` bash script and I do not see any `docker pull`s after the `docker push`es https://github.com/concourse/docker-image-resource/blob/c725c6277ca2820016de1bfe2bdfabaad5fd5879/assets/out#L241 

Where in the resource is this `docker pull` child being created?

![image](https://user-images.githubusercontent.com/100825/42265710-22cf8320-7f29-11e8-94a3-70013a7201aa.png)

**Comment by chrishiestand** [comment]
If someone wants to document it in this issue, I'll write up a PR for the README

**Comment by vito** [comment]
This is a property of Concourse, not just this resource: https://stackoverflow.com/questions/38964299/why-does-concourse-get-a-resource-after-puting-it

You can tell the resource to not download on the implicit `get` step like so:

```yaml
put: foo
params: {...}
get_params: {skip_download: true}
```

**Comment by chrishiestand** [comment]
@vito Thank you so much. Yeah sorry I totally forgot about that (having read it when I didn't really understand anything about concourse). And I totally agree this shouldn't be repeated everywhere. However, imo, I've found that humans are not very good at reading/grokking documentation and so the most user friendly documentation does repeat itself at common confusion points. I will try to grok and generate a PR that is user friendly.

Alternatively, if you wanted to make sure that resource is available for subsequent steps, wouldn't you have to specify:

```yaml
put: foo
params: {...}
get_params: {save: true}
```

**Comment by vito** [comment]
@chrishiestand Yeah, agreed re: occasional duplication. I think it'd be fine to call it out somewhere in the README.

Re: your example, `save: true` just modifies how it's saved (i.e. `docker save` rather than the default). By default `get` downloads and extracts the image (so it can be used for `image_resource` and `image:` on tasks).
