### ISSUE TITLE
waiting for docker to come up... forever

### ISSUE THREAD

**Issue by keithkroeger** [concourse/docker-image-resource#215]
# Bug Report

We are seeing jobs that enter a loop at:
https://github.com/concourse/docker-image-resource/blob/master/assets/common.sh#L83

This is happening when running at scale and, when we enter this loop, we never exit the loop.
Is there something that can determine why this loop will never end?  We've seen 10h plus and then kill it.

We assume that docker info is failing, but the results of docker info aren't output to any logs so that there is no further information available.

Are there any details to help debug?  Shouldn't there be some error trap, perhaps, or a timeout?

The following can also be handy:

* Concourse version: 3.13.0 (stemcell 3468.22)
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Did this used to work?  Yes

**Comment by vito** [comment]
You could try intercepting the container and looking for logs under `/tmp`:

```
fly -t <target> intercept -j <pipeline>/<job> -s <step name>
```

**Comment by keithkroeger** [comment]
Thank you for writing.  We will try this.  However, the few times we tried to intercept containers in this state, the intercept failed to connect.

**Comment by keithkroeger** [comment]
We are seeing this now and we an not connect.
Error:
```
root@OPS:/# fly -t s i -j ecc-hello-world/ci
1: build #1, step: build, type: get
2: build #1, step: common-concourse-tasks, type: get
3: build #1, step: eventing-resource, type: get
4: build #1, step: repo, type: get
choose a container: 3
error: websocket: bad handshake 
```

**Comment by robtec** [comment]
+1

**Comment by colmtuohy** [comment]
+2

**Comment by vito** [comment]
We've determined that this is a regression in recent versions Docker. On a busy worker it can hit a timeout error on startup, connecting to `docker-containerd`'s local socket. We'll have to make the startup code even more durable, I guess.

**Comment by keithkroeger** [comment]
Partially addressed by:
https://github.com/concourse/concourse/compare/v3.13.0-downgraded-docker but likely more thought needed in this space

**Comment by vito** [comment]
Seeing a lot of failed builds ever since merging this. Judging from the fact that it primarily affects the `bin-X` suites, it probably has something to do with a cold start.

See https://ci.concourse-ci.org/teams/main/pipelines/main/jobs/bin-testflight/builds/1392 and prior builds.
