### ISSUE TITLE
resource not working when running on coreos

### ISSUE THREAD

**Issue by databus23** [concourse/docker-image-resource#23]
This is a followup to my questions in the concourse slack channel.

I'm trying to get concourse running in docker/kubernetes on CoreOS. I'm having problems getting `concourse worker` to run properly in a *privileged* docker container. While I managed to get the worker to start, the docker-image resource is not able to start the docker daemon.
The `get` and `put` steps get stuck in a loop `waiting for docker to come up...`.
When hijacking into the resource container `/tmp/setup_graph.log` shows that it failed to mount the loop device:
```
[...]
+ mount /dev/loop1 /var/lib/docker
mount: mounting /dev/loop1 on /var/lib/docker failed: No such device or address
```
This errors boggles my mind. For an unknown reason the resource container is unable to mount the loop device it successfully configured with `losetup`. There are more then enough loop devices available and `losetup -a` shows the loop device (e.g. /dev/loop8) as being present with the /tmp/docker.img.XXXX. I'm able to mount this loop device from the host system and from inside the privileged docker container running the worker but not from within the garden container.

The docker daemon then itself fails to start with rather short and non-descriptive error:
```
time="2016-02-29T13:39:02.815050686Z" level=warning msg="devmapper: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option"
time="2016-02-29T13:39:02.854841326Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
```
I think it might suffer from the same underlying problem that the `devmapper` driver somehow is not able to setup its loop devices but I'm not sure.

I noticed that `/sys` is mounted `ro` in the resource container but remounting it `rw` unfortunately does nothing to fix the problem.

I'm spend quite some time trying to figure this out but I'm pretty out of ideas at this point. I would gladly appreciate it if somebody could help me debugging this. I'm pretty excited about the idea to have concourse running in kubernetes and would really like to get this working.

I cobbled together a small vagrant based project to reproduce the problem:
```
git clone https://github.com/databus23/coreos-concourse.git
cd concourse-coreos/
./setup.sh
#When concourse comes up and triggered the first build the container can be hijacked with
./fly -t vagrant hijack -j test/test /bin/sh
```
Note: This project contains a rebuild v0.74.0 `concourse` binary with a patched [setup.sh](https://github.com/databus23/coreos-concourse/blob/master/build/linux/bin/setup.sh#L41) to have garden-linux not trip over cgroup subsystems mounted as pairs (e.g. `cpu,cpuacct`). Moreover it contains the latest [docker-image-resource](https://github.com/concourse/docker-image-resource/commit/59c9f488f3da5aba969b0f162379cadeb1d7b179) to address similar issues in the docker-image resource. The build instructions can be found in the `build/` subdirectory.

The error happens on CoreOS stable, beta and alpha which ranges from kernel 4.2.2 to 4.4.1 and docker 1.8.3 to 1.10.1

/cc @vito

**Comment by vito** [comment]
I don't seem to have access to https://github.com/databus23/concourse-coreos - is that the right URL?

**Comment by vito** [comment]
Ah found it: https://github.com/databus23/coreos-concourse

**Comment by databus23** [comment]
@vito Ah, sorry my bad. I updated the instructions. Let me know if I can be of any further assistance in debugging this.

**Comment by vito** [comment]
Been looking into this all day, so far I'm stumped. `strace` just shows `mount()` returning `ENXIO`, which ain't very helpful; would need to dig into the kernel to see where that's actually coming from, which isn't fun. I was able to run the same `mount` command just fine on the host, but the moment I enter the container's mount namespace, it returns the error instead.

**Comment by databus23** [comment]
Yeah, same here. Bummer. At leasts its 100% reproducible. Any ideas on how to proceed? I'm not that familiar with garden linux and https://github.com/cloudfoundry-incubator/garden-linux/issues/45 is crushing my hopes to get support from the garden linux project. Is the linux-backend really only supported on Ubuntu? D you think its worth digging deeper or are there viable alternatives to the linux backend on the horizon that will work on more platforms ? From what I read the plan is to replace the current linux backend by a runC implementation.

I'm not really happy with running it on ubuntu as we are all in on kubernetes/CoreOS and I don't want to manage ubuntu vms anymore.

**Comment by vito** [comment]
The main focus these days is on [Guardian](https://github.com/cloudfoundry-incubator/guardian) - the aforementioned runC-based Garden backend. I have high hopes for improved portability and once it replaces Garden-Linux hopefully a bigger focus on usability.

Ubuntu is the primary target and the platform that the (pretty small) team is currently focused on supporting for production use cases, mainly to limit the scope of things the team has to worry about. I think it was tested on CentOS at one point; most things should just work, but containerization is a nightmarish hellscape to tackle when it comes to portability (kernel versions alone change everything).

/cc @julz @goonzoid (Garden PMs/contributors who I don't want to speak too much for)

**Comment by databus23** [comment]
For what its worth, I got a PR in garden-linux handling grouped cgroup mounts (https://github.com/cloudfoundry-incubator/garden-linux/pull/62). Still no luck with running a worker on cores though. The mount namespace inside the garden container is still acting up.

**Comment by pauldub** [comment]
Hi, I would like to report the same issue happening on an Ubuntu 14.04 server (from scaleway.com).

Some basic informations about the box: 

```paul@concourse-worker-1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
paul@concourse-worker-1:~$ uname -a
Linux concourse-worker-1 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

What informations would you need to debug this issue? Can I help?

**Comment by vito** [comment]
This will be fixed in the next release; we've confirmed this is working with the beta binaries available here:

https://github.com/vito/bin/releases
