### ISSUE TITLE
Support for Buildpack V3

### ISSUE THREAD

**Issue by daniellavoie** [concourse/docker-image-resource#269]
That is a long shot!

[buildpacks,io](https://buildpacks.io) is just awesome. I've been thinking about how could a concourse pipeline leverage that. My first iteration involved building a task with a docker image that packages `docker` and the `pack` CLI.

I would like to come up with something less verbose and closer to a "just works" experience. I started thinking about writing a resource from scratch but came to realize that everything that the `docker-image-resource` does would have to be re-implemented in this hypothetical `buildpack-resource`.

At the end of the day, we would only need to swap the `docker build` command from the `out` script to a `pack` command if someone wants to use the buidlpack v3.

Say bye bye to Dockerfiles. Any though in this?

**Comment by vito** [comment]
Sounds neat, but it seems like it should be a task, not a change to the `docker-image` resource. You could check out the [`builder` task](https://github.com/concourse/builder-task) for an example of this pattern.
