### ISSUE TITLE
pushing to AWS ecr - credentials not found in native keychain

### ISSUE THREAD

**Issue by shopizer-ecommerce** [concourse/docker-image-resource#270]
Based on the documentation for pushing an image to aws ecr

resources:
  - name: code  
    type: git  
    source:  
      uri: https://github.com/project/repo.git
      branch: master
  - name: ecr
    type: docker-image
    source:
      repository: 113537969376.dkr.ecr.ca-central-1.amazonaws.com/repo
      access_key_id: ((AWS_ACCESS_KEY_ID))
      secret_access_key: ((AWS_SECRET_ACCESS_KEY))
jobs:  
  - name: build-ecr  
    plan: 
          - get: code 
          - put: ecr
               params:
               build: {build: code}

command looks like this
fly -t project set-pipeline -p build-ecr -c concourse.yml --var "AWS_ACCESS_KEY_ID=...." --var "AWS_SECRET_ACCESS_KEY=..."

Using concourse 4.1.0
Immediately i get this error

stderr:
failed to get ECR credentials: credentials not found in native keychain

Thanks for giving me a hint on this

**Comment by GergelyKalmar** [comment]
I was also bitten by this - in case anyone else is looking for a solution the problem for me was the permissions of the AWS user used for this operation.

You should first check if you also see the problem when trying to retrieve the ECR login credentials using the command line: `aws ecr get-login --no-include-email --profile concourse`, where concourse for me is a named profile (see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) with the same access keys as the one I use in the pipelines.

You can then attach one of the existing managed policies to your Concourse AWS user (see here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html) or create your own one if you want to. It seems to be important that you allow the "ecr:GetAuthorizationToken" action for all resources - it doesn't seem to work if you're restricting this to only some repositories.

**Comment by Sluggerman** [comment]
In most cases, it is an issue with missing IAM permissions, however if you use proxy with Concourse, mind that IAM metadata will be queried on proxy, not Concourse worker.

**Comment by xtremerui** [comment]
Is this problem solved by configuring IAM?

**Comment by xtremerui** [comment]
Thx for the update. I will close the issue then.
