### ISSUE TITLE
GovCloud endpoint support for ECR

### ISSUE THREAD

**Issue by dgershman** [concourse/docker-image-resource#276]
It looks like the packages are out of date in such a way that I'm receiving the below error when referencing a push to `us-gov-west-1`.  Is it possible to update the dependencies and cut a new version?

```shell
Error retrieving credentials: MissingEndpoint: 'Endpoint' configuration is required for this service
```

**Comment by xtremerui** [comment]
could you provide more info about how you getting that error? Like your resource config and your put step.
