### ISSUE TITLE
'registry_mirror' indiscriminately overwrites a 'repository' containing a registry hostname

### ISSUE THREAD

**Issue by mdb** [concourse/docker-image-resource#305]
In current implementation, if a `registry_mirror` is configured, images whose `source.repository` contains a registry-host-prefixed image (such as `my-registry.com/foo/bar`) will still be checked at the `registry_mirror` registry and _not_ the registry specified in the `repository` value. This may cause the `check` to fail if the configured `registry_mirror` does not mirror the registry host specified in the `repository` value, but instead mirrors a _different_ registry.

This is especially problematic when a Concourse-wide [default registry has been configured](https://github.com/concourse/concourse/pull/6079). 

For example, given the following default `docker-image` configuration:

```yaml
docker-image:
  registry_mirror: https://my-default-mirror.com
```

...and the following `docker-image-resource`:

```yaml
- name: my-image
  type: docker-image
  source:
    repository: my-registry.com/foo/bar
```

...the image is checked at `my-default-mirror.com/foo/bar`. Unless `my-default-mirror.com` is a mirror to `my-registry.com`, the `check` invocation may result in failures like the following:

```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch manifest: Head "https://my-default-mirror.com/v2/foo/bar/manifests/latest": unauthorized: BAD_CREDENTIAL
```

This prevents individual users from using `docker-image-resource` images sourced from any registry other than the registry mirrored by the default `registry_mirror`. This is particularly problematic in large Concourse installations -- such as the one my team operates, which services thousands of users -- when individual pipelines, jobs, and tasks may use `docker-image-resource` instances sourced from their own registries, or even public registries that are not mirrored by the default `registry_mirror`.

It's worth noting that this is _not_ true of `docker`, nor the [registry-image-resource](https://github.com/concourse/registry-image-resource), both of which _can_ successfully resolve `my-registry.com/foo/bar` from `my-registry.com`, even when `my-default-mirror.com` has been configured as a registry mirror. In the case of `docker`, it appears `my-registry.com/foo/bar` is successfully resolved without performing any requests to `my-default-mirror.com`.

**Comment by vito** [comment]
fixed with #306 - thanks!
