### ISSUE TITLE
Docker build/test instructions in README are out of date for Ubuntu images

### ISSUE THREAD

**Issue by apinkney97** [concourse/docker-image-resource#327]
Hi, since #320 the [instructions in the readme for running tests](https://github.com/concourse/docker-image-resource#running-the-tests) (and also for building the docker image) are out of date, or at least they are for the ubuntu image.

If you try to run
```
docker build -f dockerfiles/ubuntu/Dockerfile .
```

you get
```
[snip]
Step 15/25 : FROM ${base_image} AS resource
base name (${base_image}) should not be blank
```

Instead you now need to run something like
```
docker build -f dockerfiles/ubuntu/Dockerfile --build-arg base_image=ubuntu:latest .
```

because there is no default set for `base_image` in the ubuntu Dockerfile.

Was this a deliberate choice? I note that there is a default in the alpine Dockerfile. I think either the readme needs to be updated, or a default value for `base_image` should be added to the ubuntu dockerfile.

**Comment by xtremerui** [comment]
Thx for pointing it out. The instruction has been updated.
