### ISSUE TITLE
Should the ping also use HEAD instead of GET, to avoid rate limiting?

### ISSUE THREAD

**Issue by dfuentes77** [concourse/docker-image-resource#335]
https://github.com/concourse/docker-image-resource/blob/b15016d468bb7cc84802c1670cbf9f0c3a55ab03/cmd/check/main.go#L235

**Comment by vito** [comment]
Is that endpoint even rate limited?

**Comment by dfuentes77** [comment]
I literally asked our Docker reps, and they came back with just quoting the docs:
https://docs.docker.com/docker-hub/download-rate-limit/

All I know is I started using the `registry-image-resource` and my number of daily pulls actually went up.  After testing the `check` command inside the container, I noticed it does a more GET pings than my older version of `docker-image` built into concourse.   I don't have direct evidence but I'm suspicious of their pull numbers.  Closing in the meantime.
