### ISSUE TITLE
Alpine Does Not Support B64 Decode Long Flag

### ISSUE THREAD

**Issue by tgoodsell-tempus** [concourse/docker-image-resource#353]
In the latest version of Alpine, it does not support the `base64 --decode` option:
```
➜ docker run --rm -it alpine:latest /bin/sh
/ # base64 --help
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: base64 [-d] [-w COL] [FILE]

Base64 encode or decode FILE to standard output

	-d	Decode data
	-w COL	Wrap lines at COL (default 76, 0 disables)
```

Therefore, using the `additional_private_registries` option crashes the alpine image. Since ubuntu support both `-d` and `--decode`, using `d` should fix this.

**Comment by tgoodsell-tempus** [comment]
#352 Is the fix for this.

**Comment by mstandley-tempus** [comment]
To help others find this issue, here is the console output associated with this problem:

```
base64: unrecognized option: decode
```
