### ISSUE TITLE
docker_buildkit doesn't work?

### ISSUE THREAD

**Issue by dominicfreeston** [concourse/docker-image-resource#359]
### Describe the bug

I've enabled `docker_buildkit: 1` in the `put` step of a `docker-image` resource in my pipeline config and getting the following error:

```
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

If I `fly hijack` the container and run `apt-get update` and `apt-get install docker-buildx-plugin` this makes the error go away, which suggests to me the plugin is missing from the docker image.

Looking at the [Dockerfile in this repo I see that it installs docker but not the plugin](https://github.com/concourse/docker-image-resource/blob/master/Dockerfile#L45), so it might be as simple as adding it to the list of things to install? I'm under the assumption this is the image the `put` step runs in, but it's highly possible I have a flawed mental model of what is happening though as I'm still getting my head around how all the various pieces fit together.

### Reproduction steps

1. Add `docker_buildkit: 1` to the `params` in the `put` step of a docker-image resource
2. Set the pipeline changes
3. Try and run the pipeline

### Expected behavior

The put step works with `docker_buildkit: 1` enabled

**Comment by TheDevMinerTV** [comment]
The PR I've made fixes this ^^

**Comment by kusibornhauser** [comment]
@dominicfreeston does that mean (if the fix is applied) it is possible to use buildx? I'm interested to build for arm64 and amd64. If so, mind to share an example pipeline?

**Comment by TheDevMinerTV** [comment]
When can we expect a new Concourse CI release which bumps the docker-image resource?

**Comment by dominicfreeston** [comment]
@TheDevMinerTV - I'm not sure, I think https://github.com/concourse/oci-build-task might support this? Thanks for trying out the fix and opening the PR.
