### ISSUE TITLE
Support for docker repository cache

### ISSUE THREAD

**Issue by nkcraddock** [concourse/docker-image-resource#44]
We have the need to use a caching docker repository proxy so that we can speed up our builds by pulling docker images from our local repository instead of getting them from the official docker hub each time. 

To accomplish this, the docker daemon must be started with `--registry-mirror=https://my-docker-cache`
From [Run a local registry mirror](https://docs.docker.com/v1.5/articles/registry_mirror/)

To facilitate this, we can add a new param called `registry_mirror` to the docker-image-resource `out` and `in` and have it conditionally add this to the `docker daemon` command in `start_docker()`.

**Comment by vito** [comment]
Sounds the same as https://github.com/concourse/docker-image-resource/pull/42 - though it's good to hear the use case. We've prioritized that already and should be merging it soon.

**Comment by nkcraddock** [comment]
Oh wow. Looked through the issues and somehow missed #42. Thanks. Cheers.

**Comment by cdutra** [comment]
The pr #42 was merged.
