### ISSUE TITLE
Put should fail when `cat: can't open 'yourimagename.tar': No such file or directory` occurs

### ISSUE THREAD

**Issue by ghost** [concourse/docker-image-resource#50]
```
waiting for docker to come up...
Login Succeeded
cat: can't open 'input_volume_path/rootfs_file_name.tar': No such file or directory
sha256:1d285d20fe4bef24bd89924b5558bb34f2eee0eceb08d46db1ec8b5b5c7bd099
The push refers to a repository [docker.io/our-dockerhub-org/our-image-name]
e3b0c44298fc: Preparing
e3b0c44298fc: Pushing
e3b0c44298fc: Pushed
our.tag.number: digest: sha256:681229f14a0c2be154fa9e40357f2ecee63ecfed7310520b037c6cb1cf033e17 size: 500
```

We're not sure why this happened (output from previous step being mounted as empty volume is the  most likely culprit), but the rootfs tar archive that the docker commands were referring to didn't exist.  The resource `put` should error out in this case, because when it doesn't, it pushes a 23 byte broken docker image to our repository.

**Comment by xtremerui** [comment]
Closing due to  issue owner not exist anymore.
