### ISSUE TITLE
"concourse-web" container is failing and "concourse-worker" container cannot be removed.

### ISSUE THREAD

**Issue by cohenaj194** [concourse/docker-image-resource#61]
I'm trying to test out concourse on an ubuntu 14.04 ec2 instance.  I am attempting to use the containerized version of the software with the docker-compose example shown here in the [documentation.][1] However on any attempt the `concourse-web` container fails after about 15 seconds. 

**More info:**

Here is the script I am using to get it up and running:

    mkdir concourse
    cd concourse
    mkdir -p keys/web keys/worker
    
    ssh-keygen -t rsa -f ./keys/web/tsa_host_key -N ''
    ssh-keygen -t rsa -f ./keys/web/session_signing_key -N ''
    
    ssh-keygen -t rsa -f ./keys/worker/worker_key -N ''
    
    cp ./keys/worker/worker_key.pub ./keys/web/authorized_worker_keys
    cp ./keys/web/tsa_host_key.pub ./keys/worker
    
    # for ec2
    export CONCOURSE_EXTERNAL_URL=$(wget -q -O - http://instance-data/latest/meta-data/public-ipv4)
    
    #creating docker compose file
    echo 'concourse-db:
      image: postgres:9.5
      environment:
        POSTGRES_DB: concourse
        POSTGRES_USER: concourse
        POSTGRES_PASSWORD: changeme
        PGDATA: /database
    
    concourse-web:
      image: concourse/concourse
      links: [concourse-db]
      command: web
      ports: ["8080:8080"]
      volumes: ["./keys/web:/concourse-keys"]
      environment:
        CONCOURSE_BASIC_AUTH_USERNAME: concourse
        CONCOURSE_BASIC_AUTH_PASSWORD: changeme
        CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
        CONCOURSE_POSTGRES_DATA_SOURCE: |
          postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    
    concourse-worker:
      image: concourse/concourse
      privileged: true
      links: [concourse-web]
      command: worker
      volumes: ["./keys/worker:/concourse-keys"]
      environment:
        CONCOURSE_TSA_HOST: concourse-web' > docker-compose.yml
    
    docker-compose up -d

However about 15 seconds after doing a `docker-compose up -d` the `concorse_concourse-web_1` container stops running and I cannot connect to it through a browser at any point.  Here are the docker logs of the container at the end right when it fails:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x5e093a]
    
    goroutine 1 [running]:
    panic(0xfba6c0, 0xc820016070)
            /usr/local/go/src/runtime/panic.go:481 +0x3e6
    github.com/concourse/atc/atccmd.(*ATCCommand).constructAPIHandler(0xc82023c608, 0x7ff484d1b5d0, 0xc8200501e0, 0xc82026f0e0, 0xc8202c9300, 0x7ff484d1d858, 0xc82030c5c0, 0x7ff484d1d980, 0xc8202afda0, 0x7ff484d1d958, ...)
            /tmp/build/9674af12/concourse/src/github.com/concourse/atc/atccmd/command.go:787 +0x121a
    github.com/concourse/atc/atccmd.(*ATCCommand).Runner(0xc82023c608, 0xc820270d30, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
            /tmp/build/9674af12/concourse/src/github.com/concourse/atc/atccmd/command.go:221 +0xe44
    main.(*WebCommand).Execute(0xc82023c608, 0xc820270d30, 0x0, 0x1, 0x0, 0x0)
            /tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/web.go:54 +0x297
    github.com/concourse/bin/vendor/github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7ff484d0b5e0, 0xc82023c608, 0xc820270d30, 0x0, 0x1, 0x0, 0x0)
            /tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:30 +0x81
    github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8200512c0, 0xc82000a150, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
            /tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/parser.go:312 +0xa34
    github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc8200512c0, 0x0, 0x0, 0x0, 0x0, 0x0)
            /tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/parser.go:185 +0x9b
    main.main()
            /tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/main.go:29 +0x10d

Also after trying to stop and remove the containers the concorse_concourse-worker_1 container cannot be removed and shows up in a `docker ps -a` as Dead.  The following error message occurs when attempting to remove it:

    ubuntu@ip-172-31-59-167:~/concorse$ docker rm a005503d568b
    Error response from daemon: Driver aufs failed to remove root filesystem a005503d568b4931f860334e95ff37265dc0913083d3592f0291e023275bbf20: rename /var/lib/docker/aufs/diff/9bcff3a39934ea3525bf8a06ef900bf9dfba59a5187747beb65e9ba5709ebf75 /var/lib/docker/aufs/diff/9bcff3a39934ea3525bf8a06ef900bf9dfba59a5187747beb65e9ba5709ebf75-removing: device or resource busy

  [1]: https://concourse.ci/docker-repository.html

**Comment by vito** [comment]
`$CONCOURSE_EXTERNAL_URL` needs to be a full URL, whereas in your script I think it'll just be the IP. I'm not sure why it'd be panicking though, we should have validations for that. [Here's the line of code.](https://github.com/concourse/atc/blob/cb07ea81d31ef6e55d578674371df24c781555af/atccmd/command.go#L787)

**Comment by cohenaj194** [comment]
@vito Yep setting the external IP address as a full address for:

     CONCOURSE_EXTERNAL_URL: "http://${CONCOURSE_EXTERNAL_URL}/"

Fixed it and now the "concourse-web"  container stays active.  

I still have the issue of the "concourse-worker" container.  At the moment the only fix for it is either restarting the docker service or rebooting the machine.  The biggest issue with this containers failure is that the dead containers are not completely removed from the memory of the machine and after a few attempts the `/dev/xvda1` volume slowly fills up causing a number of issues.

**Comment by vito** [comment]
Not sure what's up with that aufs error. Sounds like it's coming from Docker, so I don't have a lot of hope in being able to fix it. If you switch to the `btrfs` graph driver in Docker you'll probably have a better time.
