### ISSUE TITLE
Configure docker to use a different IP range

### ISSUE THREAD

**Issue by vito** [concourse/docker-image-resource#65]
See https://github.com/petertrotman/concourse-docker/commit/190fbffd6e130cc3741c8abf27fb815218228b4a

(If that goes down: it's an example of Docker Composing Concourse with a registry.)

This doesn't work as the outer Docker Compose'd registry lives on the 172.x.x.x address range, Docker's default. As soon as we spin up Docker in the container, it clobbers that range with its own, making the registry unreachable.

**Comment by chendrix** [comment]
Closing as solved by concourse/concourse#1145 😝
