### ISSUE TITLE
Garden MTU is ignored when starting docker daemon

### ISSUE THREAD

**Issue by manno** [concourse/docker-image-resource#67]
As discussed in https://github.com/concourse/concourse/issues/551 garden can be configured to use a specific interface MTU.

However docker-image-resource ignores that MTU. This leads to connection problems on certain networks, while building docker images. 

[Hard coding the MTU to match our network](https://github.com/manno/docker-image-resource/commit/288fb29bfd1876e724055ba252d13ee5a778e43d)  stops zypper, called from inside the Dockerfile, from freezing.

**Comment by databus23** [comment]
Since docker 1.11 (https://github.com/docker/docker/commit/fd9d7c02fcc8edd73d056f56f17e5cfe1760495b) docker is not adopting the MTU from the default interface anymore.

For the docker resource this could be easily fixed by adding something like this to `start_docker`
```
local mtu=$(cat /sys/class/net/$(ip route get 8.8.8.8|awk '{ print $5 }')/mtu)
local server_args="--mtu ${mtu}"
```

**Comment by mdomke** [comment]
I have the same problem with running docker inside a garden container on OpenStack with concourse. The MTU setting is not being promoted properly and especially SSL based connections (e.g.: downloading a tar-archive over HTTPS) fail. I manually verified that the proposed changes from @databus23 would solve the problem. Is anyone planing on creating a pull-request therefore or should I take my chances?

**Comment by mdomke** [comment]
Another option would obviously be to make the `server_args` a configuration value of the resource. @vito what do you think about this?

**Comment by mdomke** [comment]
I created a drop in replacement image with the suggestions from @databus23, which people can use until this issue is fixed here. It's `mdomke/docker-image-resource`

**Comment by vito** [comment]
@mdomke I'm not a fan of open-ended params like `server_args` in general as it tightly couples us to the docker CLI. `check` for example was rewritten to not use the daemon at all, and if we had done configs like that everyone would have to change their pipelines.

A PR would be great!
