### ISSUE TITLE
skip_download not working

### ISSUE THREAD

**Issue by SillyMoo** [concourse/docker-image-resource#68]
I have found that skip_download is not working. The issue appears to be that even if the image is not download 'docker inspect' is called. But there is no image to inspect so it fails.

**Comment by vito** [comment]
Sorry about that. Just fixed.

**Comment by SillyMoo** [comment]
I'm afraid that this fix actually stops the regular (non-skip download) case fail. The reason is that now you are calling 'image_id="$(image_from_digest "$repository" "$digest")"' before the image for the current version has been pulled down.
Since image_from_digest calls docker_image to try find the image id it has to have been pulled before you can call this (this currently causes the docker inspect in the usual path to fail.

**Comment by vito** [comment]
should be fixed in the commit after it

**Comment by SillyMoo** [comment]
Coolios. Cheers
