### ISSUE TITLE
Stops working if digest disappears from Artifactory registry

### ISSUE THREAD

**Issue by SillyMoo** [concourse/docker-image-resource#69]
I am finding that the check script fails if the previous digest can't be found. This can happen if, for example, you are looking for 'some_repo:latest' and a new image is pushed to 'some_repo:latest' outside of the control of concourse.
In this case the old image layers can get garbage collected, and so the manifest can't be retrieved using the previous digest, and a fatal error occurs. The check job never recovers.

**Comment by vito** [comment]
It *should* work, unless the registry gives some weird reply. We handle 404:

https://github.com/concourse/docker-image-resource/blob/master/cmd/check/main.go#L123

**Comment by SillyMoo** [comment]
I've not debugged it yet, but I assumed you would fail to build the cursor here: https://github.com/concourse/docker-image-resource/blob/master/cmd/check/main.go#L91

**Comment by SillyMoo** [comment]
Oh wait, on second thoughts, I see a 500, not a 404. So that'll be the problem I guess.

**Comment by SillyMoo** [comment]
(it's jfrog artifactory)

**Comment by vito** [comment]
Pretty sure that line would only fail with validation errors. And yeah, if it's returning a 500 that'd be an issue.

**Comment by SillyMoo** [comment]
Stoopid artifactory. I guess as 500 is not a good return code this won't get resolved in the official repo?

**Comment by SillyMoo** [comment]
Ok. I'm going to try and make an argument that this should be fixed in the official repo. Firstly there is the fact that artifactory is pretty popular, so supporting it is legit. But also you know that you were able to get the latest digest (so there is not a general server error), so the fact that the server threw an error on the specific historic manifest (regardless of the error code) seems to fall under this clause in the 'implementing a resource' guide:

If your resource is unable to determine which versions are newer then the given version (e.g. if it's a git commit that was push -fed over), then the current version of your resource should be returned (i.e. the new HEAD).

**Comment by vito** [comment]
Agreed, to a point. If there are *predicted* errors then the resource should fall back on yielding the current version. Otherwise it should expose them, so that you can find out that e.g. your Docker registry is blowing up, rather than having your resources silently start to misbehave.

Unfortunately it sounds like Artifactory has a nonstandard API, but I agree that we should handle it. I wonder if they return a sane response body at least?

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
