### ISSUE TITLE
Parsing Repository Bug

### ISSUE THREAD

**Issue by masterjk** [concourse/docker-image-resource#71]
When specifying a repository URL in a concourse task, was getting this error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
malformed repository url
```

From investigating further, found the parsing code can only handle up to 1 folder deep.  See https://github.com/concourse/docker-image-resource/blob/master/cmd/check/main.go#L258-L276

WORKS: registry.domain.com/1/image
FAILS: registry.domain.com/1/2/image

Unless there is a requirement that docker image registries can only go one folder deep?

**Comment by vito** [comment]
Is it valid to have a registry URL with that many path entries? What's an example of that? I'm not sure what it'd even mean semantically.

**Comment by TiraO** [comment]
I ran into this issue on my project-- We were trying to use Nexus to store our docker images (https://books.sonatype.com/nexus-book/3.0/reference/docker.html#docker-registry-api) and its api sits below several slashes in the url. I think the assumptions parseRepository makes about the meaning of docker urls are a bit too broad. In the case of nexus, its urls are of the form `<nexus-hostname>:<repository-port>/<namespace>/<image>:<tag>`. Namespace can be several levels deep as well.

**Comment by spicykaiju** [comment]
Experiencing the same issue as @TiraO with our Nexus repo. Our URL isn't as deep however:
acme.co.com/repository/docker-registry/image:tag

Would it be possible to get this addressed ASAP? I'm building a new CI/CD system with Concourse, and this is a showstopper for us.

**Comment by jtarchie** [comment]
This looks like it was resolved with https://github.com/concourse/docker-image-resource/commit/b45f799d99ce192b74e72d5c4f2b55f707bd010a. Can anyone confirm that this is the same issue?

**Comment by xtremerui** [comment]
Closing see comment above. If there is still problem related to repo URL parsing feel free to open new issue.
