### ISSUE TITLE
tag_prefix uses string, not file path

### ISSUE THREAD

**Issue by jtarchie** [concourse/docker-image-resource#84]
The `tag_prefix` option on `put` is not loading from filename. It actually just get's [concatenated](https://github.com/concourse/docker-image-resource/blob/c9ee6c2b685d2f17e2fefbfc8b456a2dea5d16fc/assets/out#L63) with `tag_params`, which does load from a file.

**Comment by vito** [comment]
Sorry what's the issue here? Do you need it loaded from a file?

**Comment by jtarchie** [comment]
I need to read the docs better. It said from a file, but it is from the `tag` it meant. Sorry, long weekend.

**Comment by vito** [comment]
ah, yea it is worded a bit confusingly. no worries!
