### ISSUE TITLE
Parsing of digest fails while running Concourse in docker for mac

### ISSUE THREAD

**Issue by svdberg** [concourse/docker-image-resource#97]
I have the following pipeline snippet:
`
  - name: tenant-docker-image
    type: docker-image
    source:
      email: {{docker-repo-email}}
      password: {{docker-repo-password}}
      repository: {{docker-repo}}
      tag_as_latest: true
`

that is used as:
`
  - put: tenant-docker-image
    params:
      build: workspace
      tag: workspace/version
`
where `workspace` contains a file `version` with the git hash to use as version.

This yields the following output during build:
`
Pushing tag for rev [854f1a846914] on {https://*************.so:443/v1/repositories/aurora/aurora-cas-tenant-frontend/tags/e219cbcc4a90a8f58d7f90a76c771c8c6fa8da47}
`
The next step is to `pull` this repository which shows a regex problem:

`
Error parsing reference: "******************:443/aurora/aurora-cas-tenant-frontend@for" is not a valid repository/tag
`
As you can see it tried to parse the last line using `digest="$(tail -1 push-output | awk '{print $3}')"
` and that gave "for", whereas it should have given the rev or even the whole URI.

**Comment by svdberg** [comment]
Docker for mac version `1.13.1 (15353)`

**Comment by svdberg** [comment]
Looks like the output for Docker Hub is quite different:
`Digest: sha256:207a64b578c1254215f69bb7b9b08b81e051be25209f610f2855c2ac71939104`

I'm checking now what version of the docker registry we are running.

**Comment by chendrix** [comment]
@svdberg did you ever figure out what the issue here was?

I'm inclined to close this until we find more definitive proof of this being a concourse problem.
